name: Run Azure Login with OpenID Connect
on: 
  workflow_dispatch:

permissions:
      id-token: write
      contents: read
      
jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

              # uri="https://management.azure.com${rid}?api-version=2024-03-01-Preview"

          # echo $uri
          
          # az rest --uri "$uri" > search.json
          # jq '.properties.networkRuleSet.bypass = "AzureServices"' search.json > search_updated.json
          # az rest --uri "$uri" \
          #   --method PUT \
          #   --body @search_updated.json